[data]
train_bin = "data/fineweb350B-dedup-suffix-31/fineweb350b-dedup_train_*.bin"
val_bin = "data/fineweb350B-dedup-suffix-31/fineweb350b-dedup_val_*.bin"

[model]
n_layer = 8
# We fix d_head = 64, so 256/64 = 4 heads
n_head = 4
n_embd = 256
block_size = 64
vocab_size = 151936
weight_tying = false

[training]
max_iters = 1e6
batch_size = 512
gradient_accumulation_steps = 4
eval_interval = 500
always_save_checkpoints = true
eval_iters = 1
seed = 64
log_interval = 10

[optimizer]
learning_rate = 2e-5
# So adamw = adam
weight_decay = 0

[system]
compile = true
dtype = "bfloat16"

[logging]
wandb_log = true
wandb_project = "translation-compression"
wandb_run_name = "65535-domain-translations-fineweb-8-256-prototype"
wandb_notes = "65535 domain on fineweb"
wandb_group = "dw-2-1-dry-runs"

[experiment]
n_compartments = 65535
compartment_scaling = "unequal"
translation_ratio = 0
max_compartments = 65535
assignment_seed = 64
# shared_token_embeddings = true
use_compartment_embeddings = true
# copy_compartment_lm_head = true
permute_tokens_per_compartment = true
